In [1]:
import pandas as pd
import numpy as np

In [2]:
Data_jantung = pd.read_csv("C:\\Users\\62813\\Downloads\\GitHub\\DM_Ade_2022\\heart.csv")
Data_jantung.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [3]:
x = Data_jantung.drop(["output"], axis = 1)
x.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  
0    0      1  
1    0      2  
2    0      2  
3    0      2  
4    0      2

In [4]:
# Variabel dependen
y = Data_jantung["output"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: output, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [7]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 4)

In [8]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [9]:
y_pred = knn.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [10]:
knn.predict_proba(x_test)

array([[1.  , 0.  ],
       [0.75, 0.25],
       [0.25, 0.75],
       [0.5 , 0.5 ],
       [0.5 , 0.5 ],
       [1.  , 0.  ],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.25, 0.75],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.25, 0.75],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.  , 1.  ],
       [0.75, 0.25],
       [0.75, 0.25],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.75, 0.25],
       [1.  , 0.  ],
       [0.25, 0.75],
       [0.25, 0.75],
       [0.75, 0.25],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.75, 0.25],
       [1.  , 0.  ],
       [0.25, 0.75],
       [0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.75, 0.25],
       [1.  ,

In [11]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[22,  6],
       [ 7, 26]], dtype=int64)

In [12]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      0.79      0.77        28
           1       0.81      0.79      0.80        33

    accuracy                           0.79        61
   macro avg       0.79      0.79      0.79        61
weighted avg       0.79      0.79      0.79        61

